// Generated by `talks generate example-talk` on 2026-10-01 from brief.yaml.
// Edit freely; regenerate with --force to overwrite.
#import "/themes/karthein.typ": *

#show: karthein-theme.with(
  config-info(
    title: [Example Talk: Reproducible Slides From a Curated Library],
    author: [Your Name],
    institution: [Texas A\&M University],
    date: [Oct. 1, 2026],
    event: [Example Meeting],
  ),
  sponsors: false,
  handout: sys.inputs.at("handout", default: "false") == "true",
)
#set document(title: "Example Talk: Reproducible Slides From a Curated Library", author: "Your Name")

#title-slide(contents: ([The pipeline], [A figure from the catalog],))

// ---- block example-intro (2.0 min): What this template gives you
#sponsors(false)
#include "/blocks/example-intro.typ"

// ---- block example-figure (2.0 min): A catalogued figure on a slide
#sponsors(false)
#include "/blocks/example-figure.typ"
